site_name: AuxBot Documentation

repo_name: Auxtal/AuxBot-Python-Docs
repo_url: https://github.com/Auxtal/AuxBot-Python-Docs
edit_uri: ""

theme:
  favicon: assets/AuxBot.png
  logo: assets/AuxBot.png
  name: 'material'

  features:
    - header.autohide

  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode